name: Documentation

on: [push, pull_request]

jobs:
  Documenter:
    if: github.repository == 'Hirlam/SystemWW'    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Build and deploy 
        run: julia --project=. make.jl  
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
  
